### ISSUE TITLE
About MongoDB connection option "authMechanismProperties.ssapiServiceRealm"

### ISSUE THREAD

**Issue by noteon** [mongodb-js/kerberos#102]
I did not find an implementation of the MongoDB kerberos connection option "authMechanismProperties.SERVICE_REALM" in the source code. I would like to ask, is the option ssapiServiceRealm available or  is there a plan to implement the option?

SERVICE_REALM:<string>
Set the Kerberos realm for the MongoDB service. This may be necessary to support cross-realm authentication where the user exists in one realm and the service in another.

**Comment by mbroadst** [comment]
Hi @noteon, we don't explicitly use the value, but it is supported by providing a username with the realm in it (aka the "principal"). Have you tried this?

**Comment by noteon** [comment]
> Hi @noteon, we don't explicitly use the value, but it is supported by providing a username with the realm in it (aka the "principal"). Have you tried this?

@mbroadst  You mean: as long as it is configured in mongodb URI, it can work directly?

e.g.

const mongodb = require("qh-mongodb"); //npm i mongodb
const {
    MongoClient
} = mongodb;

const client = await MongoClient.connect(`mongodb://mongodb/user@kdc.com:pwd@mongodbserver.com:27017/?authMechanism=GSSAPI&authMechanismProperties=SERVICE_REALM:test.com&authSource=$external`);
//authMechanismProperties=SERVICE_REALM:test.com

Sorry, I don't have a kerberos realm override test environment, I just want to ask if the feature has been implemented.

**Comment by mbroadst** [comment]
Yes, that should work. I've created [NODE-2026](https://jira.mongodb.org/browse/NODE-2026) to track explicit support of the {{SERVICE_REALM}} option, thanks for your question

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket.  Thanks!
