### ISSUE TITLE
initializeServer is not implemented yet for Windows

### ISSUE THREAD

**Issue by engineertdog** [mongodb-js/kerberos#105]
I have been looking around for an NPM package for Node that would allow me to send requests (using Axios) that I could authenticate with the native Kerberos authentication. Which led me to this package.

Unless I'm mistaken, I would want to call `kerberos.initializeServer` for a NodeJS application to be able to authenticate the user, correct? However, that leads to the error in the title.

This is a program that will run on a Windows 2012 server. The majority of my authentication needs come from setting up Web Socket connections with the `ws` NPM package. Authentication to the API endpoints being accessed on the WSS connection can be done with basic authentication by passing the username and password of the Windows Service Account to the connection string. However, this is obviously not secure, and I'd like to be able to use Kerberos authentication instead. I have a dedicated SA that can be used to authenticate with Kerberos.

**Comment by oldrich-s** [comment]
Try to use `node-sspi` instead. This did the job for me:

```
const Http = require('http')
const NodeSSPI = require('node-sspi')

const server = Http.createServer()

server.on('request', (req, res) => {
    var nodeSSPI = new NodeSSPI({})
    nodeSSPI.authenticate(req, res, function(err){
      res.end(req.connection.user)
    })
})

server.listen(80, '0.0.0.0')
```

**Comment by engineertdog** [comment]
Thank you for the response. I wasn’t specific in the OP, but this is going to be a NodeJS **only** application. So, there would be no way to authenticate via an HTTP server, because there is none. 

I would need the Kerberos authentication to happen with a service account’s name and password hard coded, or for the authentication to occur based on the user that runs the application. Most of the Kerberos authentication I have seen use a web interface to make that happen, so I wasn’t sure if this would be possible. I thought this package would, but it doesn’t work on Windows, which is where I need it.

**Comment by daprahamian** [comment]
Created https://jira.mongodb.org/browse/NODE-2238 to track.

**Comment by engineertdog** [comment]
I made an update to the original post, in case you want to use the modified description. I was up late and have changed the structure of what I'm doing.

**Comment by dannydeut** [comment]
What about https://github.com/mongodb-js/kerberos/pull/97?

**Comment by acecoder93** [comment]
Is there any update for how this issue with initializeServer has been resolved for Windows? The PR was never merged, and I wanted to see if anyone came across a solution. Thanks in advance.

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket.  Thanks!
