### ISSUE TITLE
npm install kerberos fails on node v11.0.0

### ISSUE THREAD

**Issue by Anonym-Bruker** [mongodb-js/kerberos#106]
When trying to run npm -verbose install kerberos I do get an error:
> -> kerberos@1.1.3 install C:\dev\app\krimstadsok\node_modules\kerberos
> -> prebuild-install || node-gyp rebuild
 
> prebuild-install info begin Prebuild-install version 5.3.2
> prebuild-install info looking for cached prebuild @ C:\Users\username\AppData\Roaming\npm-cache\_prebuilds\1ac7ac-kerberos-v1.1.3-node-v67-win32-x64.tar.gz
> prebuild-install http request GET https://github.com/mongodb-js/kerberos/releases/download/v1.1.3/kerberos-v1.1.3-node-v67-win32-x64.tar.gz
> prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443__

When looking under https://github.com/mongodb-js/kerberos/releases there is no v67 there, only v64 
What am i doing wrong?

**Comment by Anonym-Bruker** [comment]
> @Anonym-Bruker it looks the error you have is related to accessing github.com. I believe the reason we don't have a prebuild for node v11 is because it only builds for LTS versions.

I try to do this "offline" only, as I don't have access to the internet from my virtual machine.
Is it possible to do my own build of this?
(I tried to do this on a Windows 10.0 virtual machine)

**Comment by mbroadst** [comment]
@Anonym-Bruker prebuild should fallback to building the code locally if anything fails. Do you have more of a stack trace for us to work with?

**Comment by Anonym-Bruker** [comment]
Yes, but the I guess I need to install something that could build it.
I will first try to downgrade to Node10.15.3 and see if that works...

**Comment by mbroadst** [comment]
@Anonym-Bruker yes you will, please refer to the [requirements](https://github.com/mongodb-js/kerberos#requirements) section of our readme.

**Comment by Anonym-Bruker** [comment]
This gives me headache...
I cannot due "Optiosn 1" since I am offline.
And in "Option 2" I currently only have "Visual studio code", which probably don't include the VCBuild?....
(I am starting to really dislike Node... It is a real pain when offline...)

**Comment by mbroadst** [comment]
You need to source the files somehow. If you’re just using the mongodb driver you don’t need to have this installed. But you would need to download other dependencies as well. Another option you have is prebuilding the `node_modules` and put it in place yourself. Npm install on another machine, and then copy a tarballs of your modules and drop them in
