### ISSUE TITLE
initializeServer not working as expected !

### ISSUE THREAD

**Issue by HK321** [mongodb-js/kerberos#107]
I have been working on implementing SSO in a NodeJS application using an AD hosted on an azure VM. I am using npm Kerberos in my application. Here is how I have configured my everything:

- I have created an SPN for the service 
- Generated a keytab with that SPN
- Replicated keytab in my ubuntu server /etc/
- Installed kerberos client and configued krb5.conf accordingly

In my apllication I have installed kerberos npm:
- principalDetails method return HTTP/enpast.com@REALM.COM which is what I want.
- checkPassword also works all good.
- initializeServer fails using the SPN that I get from principalDetails.

Here is the error message I get:

>  [Error: Unspecified GSS failure.  Minor code may provide more information: No key table entry found matching HTTP\/enpast.com/screwsso.eastus.cloudapp.azure.com@]

Any leads to the cause will be highly appreciated. Thank you

**Comment by Logeswaranbca** [comment]
I'm also got this error, how to clear this Error 

[Error: Unspecified GSS failure. Minor code may provide more information: No key table entry found matching HTTP@...COM]

**Comment by TheEYL** [comment]
Hey, how did you solve this issue?

**Comment by yurayko** [comment]
Try without REALM.COM and @ instead /
kerberos.initializeServer("HTTP@enpast.com")
