### ISSUE TITLE
node 12 (v72) prebuild for win 64

### ISSUE THREAD

**Issue by bigianb** [mongodb-js/kerberos#110]
Hi, in issue #99 it was said that all the prebuilds for v72 were uploaded. When I look though, I cannot see the node win64 prebuild for v72, I only see a v64  build. I can see the v72 build for linux ... just not windows 64.

I'm looking here: https://github.com/mongodb-js/kerberos/releases/tag/v1.1.3

Am I missing something?

**Comment by mmontes11** [comment]
Same as darwin x64:
https://github.com/mongodb-js/kerberos/issues/112
