### ISSUE TITLE
Is there a way to set the location of the keytab?

### ISSUE THREAD

**Issue by TheEYL** [mongodb-js/kerberos#115]
I'm getting a` Principal not found in keytab` error when running the library on my linux server. I can't use the default keytab at `/ete/krb5.keytab` because it's used by another application. Is there a way to change the defaults? It is not clear from the documentation nor from the code (I'm no C++ expert).

**Comment by fkudr** [comment]
@TheEYL try this `$ export KRB5_KTNAME=~/myspecial.keytab`

**Comment by mbroadst** [comment]
@TheEYL sorry we missed your issue. @fkudr is correct, you can use that environment variable to change which keytab krb5 uses. In the future for a more prompt reply, please open a JIRA ticket against the NODE project
