### ISSUE TITLE
How work

### ISSUE THREAD

**Issue by justknife** [mongodb-js/kerberos#120]
I only found old guides for using this package, so I wanted to clarify.
What authGSSServerStep functions have been replaced with and how it works now.
And what has changed in authGSSServerInit
**Kerberos Version:** 1.1.4

**Comment by Fran33** [comment]
I learned the same thing, and am looking for the same thing.  I am also having trouble building the component for my nodejs server, are there installation steps somewhere? I think mine is silently failing due to a missing build tool, but not sure.

**Comment by justknife** [comment]
I found some hints in the tests, but I cannot fully figure out how the structure of the request has changed.

**Comment by justknife** [comment]
`kerberos.initializeServer(service, function(err, server) {
			//check ticket
			console.log(server);
			console.log(service);
			server.step(ticket, function(err, context) {
				//in success context contains username
				ad.findUser(context.username, function(err, user) {
					//get user groups
					//if need filter by group name
					// var opts = {filter: '&(member:1.2.840.113556.1.4.1941:=' + user.dn + ')(sAMAccountName=Ex*)'};
					let opts = { filter: '&(member:1.2.840.113556.1.4.1941:=' + user.dn + ')' };
					ad.find(opts, function(err, result) {
						res.set('WWW-Authenticate', 'Negotiate ' + context.response);

						//
						console.log('-----response-----');
						console.log(res._headers);
						let response = '<p>Имя пользователя: ' + user.cn + '</p><p>Состоит в группах:</p><ul>';
						for (let i in result.groups) {
							response += '<li>' + result.groups[i].cn + '</li>';
						}
						res.send(response);`

**Comment by justknife** [comment]
[Error: Unspecified GSS failure.  Minor code may provide more information: Ticket not yet valid]
I managed to get a response from the server about the validity of the token, but I don't know what its valid form looks like

**Comment by Fran33** [comment]
What is the proper input for initializeServer? the service principal name matching a name in the keytab, or the service type e.g. 'HTTP'?
When I use keytab name, I get the unspecified GSS error from initializeServer; When I use 'HTTP' I get success but object with null values. See issue 109 from 2018.  Then when I call step with the server and my encoded ticket, I just get the an encoded token and null err.

I do know my keytab file is found, because kerberos.principalDetails recognizes a defined principal.  
The older version of this module automatically recognized the keytab and conf files, thus no gss errors. 
Maybe there is a parameter to set this time to find the details in the keytab file?

I also have no idea what a valid token looks like. But I get the token by sending the 'WWW-Authenticate' header with a 401 error from server to client (I do that before calling initializeServer, you appear to be doing it after), and client responds with the encoded token, which worked with kerberos@0.0.24

**Comment by justknife** [comment]
my last version 
	 if 	const service = `HTTP@${ hostname }`; 
	 It work, but return zero and errror in step:
	 Error: Unspecified GSS failure. Minor code may provide more information: Ticket not yet valid
	 
	```
kerberos.initializeServer(service, (err, server) => {
			let ticket = req.headers.authorization.substring(10);
				server.step(ticket, (err, server) => {
					console.log(err);
					console.log(server);
					if (server){
						console.log(server)
					}
				});
		});
```

**Comment by justknife** [comment]
I saw my ticket, but I have no idea what the server needs, and in what form it should generally respond. Judging by the tests, the answer should be in the body, in the variable contextCompleate

> What is the proper input for initializeServer? the service principal name matching a name in the keytab, or the service type e.g. 'HTTP'?
> When I use keytab name, I get the unspecified GSS error from initializeServer; When I use 'HTTP' I get success but object with null values. See issue 109 from 2018. Then when I call step with the server and my encoded ticket, I just get the an encoded token and null err.
> 
> I do know my keytab file is found, because kerberos.principalDetails recognizes a defined principal.
> The older version of this module automatically recognized the keytab and conf files, thus no gss errors.
> Maybe there is a parameter to set this time to find the details in the keytab file?
> 
> I also have no idea what a valid token looks like. But I get the token by sending the 'WWW-Authenticate' header with a 401 error from server to client (I do that before calling initializeServer, you appear to be doing it after), and client responds with the encoded token, which worked with kerberos@0.0.24

**Comment by justknife** [comment]
```
 kerberos.initializeClient(service, { mechOID }, (err, client) => {
        expect(err).to.not.exist;

        client.step('', (err, kerberosToken) => {
          expect(err).to.not.exist;

          // attach the Kerberos token and resend back to the host
          request.get(
            { url, headers: { Authorization: `Negotiate ${kerberosToken}` } },
            (err, response) => {
              expect(err).to.not.exist;
              expect(response.statusCode).to.equal(200);

              // validate the headers exist and contain a www-authenticate message
              const authenticateHeader = response.headers['www-authenticate'];
              expect(authenticateHeader).to.exist;
              expect(authenticateHeader).to.startWith('Negotiate');

              // verify the return Kerberos token
              const tokenParts = authenticateHeader.split(' ');
              const serverKerberosToken = tokenParts[tokenParts.length - 1];
              client.step(serverKerberosToken, err => {
                expect(err).to.not.exist;
                expect(client.contextComplete).to.be.true;
                done();
              });
            }
          );
        });
```
if you look at the tests, there is a piece that is similar to the one you need. But it uses a client, not a server. I'm not sure if you start something like this, it will work, but this is the only thing that is similar in search patterns

**Comment by Fran33** [comment]
oh wow, I just got it to work. after calling initializeServer with service='HTTP@'+hostname, and calling server.step as you do,
the response handler function takes err and token as args, but the correct answer for me was in the server object itself.
Your code below, copied from above, is maybe failing because you reused the server variable name, see how I replace it below beside err.

service='HTTP@something.com';
kerberos.initializeServer(service, (err, server) => {
			let ticket = req.headers.authorization.substring(10);
				server.step(ticket, (err, token) => {
					if (server){
						console.log(server.username)
					}
				});
		});

**Comment by justknife** [comment]
> oh wow, I just got it to work. after calling initializeServer with service='HTTP@'+hostname, and calling server.step as you do,
> the response handler function takes err and token as args, but the correct answer for me was in the server object itself.
> Your code below, copied from above, is maybe failing because you reused the server variable name, see how I replace it below beside err.
> 
> ```
> service='HTTP@something.com';
> kerberos.initializeServer(service, (err, server) => {
> 			let ticket = req.headers.authorization.substring(10);
> 				server.step(ticket, (err, token) => {
> 					if (server){
> 						console.log(server.username)
> 					}
> 				});
> 		});
> ```

(node:14790) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[Error: Unspecified GSS failure.  Minor code may provide more information: Ticket not yet valid]
KerberosServer {
  contextComplete: false,
  targetName: null,
  response: null,
  username: null
}
User login: null
I suppose the environment setting is to blame.
could this be? because i tried something different and the answer always returns zero

**Comment by justknife** [comment]
HTTP@myhost.domain.local

**Comment by justknife** [comment]
> oh wow, I just got it to work. after calling initializeServer with service='HTTP@'+hostname, and calling server.step as you do,
> the response handler function takes err and token as args, but the correct answer for me was in the server object itself.
> Your code below, copied from above, is maybe failing because you reused the server variable name, see how I replace it below beside err.
> 
> ```
> service='HTTP@something.com';
> kerberos.initializeServer(service, (err, server) => {
> 			let ticket = req.headers.authorization.substring(10);
> 				server.step(ticket, (err, token) => {
> 					if (server){
> 						console.log(server.username)
> 					}
> 				});
> 		});
> ```

did you set up work on *nix?

**Comment by Fran33** [comment]
My setup works on unix. The server fields you printed do in fact start null, are they still null after you call step? Make sure you replace (err,server) with (err,token) so you preserve the server after call to step.

**Comment by justknife** [comment]
> My setup works on unix. The server fields you printed do in fact start null, are they still null after you call step? Make sure you replace (err,server) with (err,token) so you preserve the server after call to step.

i'm realy not understand 
 Minor code may provide more information: Ticket not yet valid 
 what it "not yet?"

**Comment by Fran33** [comment]
Consider ignoring the gssapi error and instead look at the server object after you call server.step
In my case that server is actually the context, and contains the decoded username.
paste in your latest code and I can note whatever still looks wrong. my code example is still above, largely unchanged.

**Comment by justknife** [comment]
> Consider ignoring the gssapi error and instead look at the server object after you call server.step
> In my case that server is actually the context, and contains the decoded username.
> paste in your latest code and I can note whatever still looks wrong. my code example is still above, largely unchanged.
I tried using your code, but it doesn't return the username from which the request was made
:с

**Comment by Fran33** [comment]
Try this, I removed the service name.
kerberos = require('kerberos');
kerberos.initializeServer('', (err, server) => {
	let ticket = req.headers.authorization.substring(10);
	server.step(ticket, (err, token) => {
		if (err){
                        res.status(500).json({"message" : "error"});
                }
			console.log(server.username);
                        res.status(200).json({"username" : server.username});
		}
	});
});

**Comment by justknife** [comment]
> Try this, I removed the service name.
> 
> ```
> kerberos = require('kerberos');
> kerberos.initializeServer('', (err, server) => {
> 	let ticket = req.headers.authorization.substring(10);
> 	server.step(ticket, (err, token) => {
> 		if (err){
>                         res.status(500).json({"message" : "error"});
>                 }
> 			console.log(server.username);
>                         res.status(200).json({"username" : server.username});
> 		}
> 	});
> });
> ```

hey ty men. See this https://github.com/nugaon/passport-kerberos-negotiation .. Hi use new function kerberos package
