### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by pendo324** [mongodb-js/kerberos#51]
So I successfully installed the npm package on Windows, but when I tried to run the win32 tests (just to see if everything was setup properly) I got an error.

Code I ran: 

```
var KerberosNative = require('kerberos').Kerberos;
var kerberos = new KerberosNative();

console.log("=========================================== 0")
console.dir(kerberos.acquireAlternateCredentials("dev1@10GEN.ME", "a"));
console.log("=========================================== 1")
console.dir(kerberos.prepareOutboundPackage("mongodb/kdc.10gen.com"));
console.log("=========================================== 2")

```

Error:

```
=========================================== 0
C:\Users\<myusername>\node_modules\kerberos\lib\kerberos.js:144
  return this._native_kerberos.acquireAlternateCredentials(user_name, password, domain);
                               ^

TypeError: this._native_kerberos.acquireAlternateCredentials is not a function
    at Kerberos.acquireAlternateCredentials (C:\Users\<myusername>\node_modules\kerberos\lib\kerberos.js:144:32)
    at Object.<anonymous> (C:\Users\<myusername>\Documents\dev\kerb\test.js:5:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

```

When I looked at the object like so: 

```
var KerberosNative = require('kerberos').Kerberos;
var kerberos = new KerberosNative();

console.log(kerberos);

```

I did actually get back an empty oject: 

```
C:\Users\<myusername>\Documents\dev\kerb>node test.js
{ _native_kerberos: Kerberos {} }

```

This is my first time trying to use this library, so sorry if this issue is not really an issue. Any help is appreciated.

**Comment by christkv** [comment]
you can't run the tests they run against an internal test environment

**Comment by pendo324** [comment]
@christkv yeah, that makes sense. Do you know why the _native_kerberos object is empty though? When I call any function, like kerberos.authGSSClientInit, for example, I get the same error 

```
this._native_kerberos.authGSSClientInit is not a function
```

**Comment by RogerGMartins** [comment]
I'm having the same issue as @pendo324 .

`var Kerberos = function() {
  this._native_kerberos = new KerberosNative(); 
}`

creates an empty object

**Comment by christkv** [comment]
That's actually correct. You need to look at the kerberos.js file to see the methods exposed

**Comment by RogerGMartins** [comment]
not sure if i follow, what i'm saying is that, in the file kerberos.js, those lines (@L4) return an empty object.

**Comment by christkv** [comment]
Have a look g at lib/auth_processes/mongodb.js

especially the Win32MongoProcessor

**Comment by RogerGMartins** [comment]
thanks I will have a look

**Comment by christkv** [comment]
are you trying to use it for something specific ?

**Comment by RogerGMartins** [comment]
getting the ticket data to use for some connectivity testing (just http calls) in some endpoints.

i was able to get the ticket data from krbclient npm pakcage, but i was curious about this one.

**Comment by christkv** [comment]
ah I've never actually attempted to use this for that be people have contributed code that should make it possible.

**Comment by ccbeloy** [comment]
Have anyone fix this issue? I'm getting the same error. npm install was successful which did build the C++ files. 

TypeError: this._native_kerberos.authUserKrb5Password is not a function

var Kerberos = require('kerberos').Kerberos;
var kerberos = new Kerberos();
kerberos.authUserKrb5Password('masked', 'masked', '', function(err, ok) {
    console.log("err:",err);
    console.log("ok:", ok);
});

**Comment by tlbdk** [comment]
Hi,

I did a quick sample program the uses the windows SSIP API, it show a http SPNEGO/Kerberos Negotiate, there is a bug in the current code that forces you to set both username and password, but the whole point of this API is that should not have to, so you need to apply the following pull request to get it working:
https://github.com/christkv/kerberos/pull/54/files

``` cc
var Kerberos = require('kerberos').Kerberos;
var kerberos = new Kerberos();
var Ssip = require('kerberos').SSIP;
var http = require('http');
var urlParser = require('url');

var curl = urlParser.parse("http://<your SPNEGO protected endpoint>/");

var requestOptions = {
 host: curl.hostname,
 port: curl.port,
 path: curl.path,
 method: "GET",
 withCredentials: false // this is the important part
};

Ssip.SecurityCredentials.acquire("Negotiate", "", function(err, security_credentials) {
	if(err) return callback(err);

	//console.log("HTTP/"+(curl.hostname));
	Ssip.SecurityContext.initialize(security_credentials, "HTTP/"+(curl.hostname), "", function(err, security_context) {
			if(err) throw err;

			var has_context = security_context.hasContext;
			var payload = security_context.payload;

			requestOptions.headers = {
				Authorization: "Negotiate " + payload
			};

			httpGet(requestOptions, function(headers) {
				//console.info(headers);
			});

			//console.info(payload);
			//console.info(has_context);
		});

	// Save credentials
	//console.info(security_credentials);
});

function httpGet(requestOptions, cb) {
	var request = http.request(requestOptions, function (response) {
		var responseContent = "";
		response.setEncoding('utf8');
		response.on('data', function(chunk) {
			responseContent += chunk;
		});
		response.on('end', function() {
			console.info(response.statusCode);
			//console.info(responseContent);
			cb(response.headers['WWW-Authenticate']);
		});
	});

	request.on('error', function (e) {
		console.log(e.message);
	});

	request.end();
}
```

**Comment by christkv** [comment]
@tlbdk this is awesome if you do not mind I would like to put this example in the readme for people who ask about using the kerberos module for non mongodb things. I'll also merge your PR tomorrow.

**Comment by tlbdk** [comment]
You are more than wellcome to do that, the example is first working version so it could use a clean up to make it a bit easier to understand. I'm planning to create a nicer wrapper to do the SPNEGO stuff on both windows, mac and linux, if I do a pull request would you be willing to accept that or would you prefer that I did a new module?

**Comment by ljani** [comment]
Hey,

I fixed the very same bug earlier this month.

Anyway, just a heads up if anyone is following the example, the SPN isn't always the hostname. In case of virtual hosting, it's possible that you need to specify the name of the real host instead of the virtual host.

**Comment by valp124** [comment]
Gents,

Please excuse my ignorance if I don't understand something here. This works for step 2 of the negotiation (http://davenport.sourceforge.net/ntlm.html), I get the expected 401 status and Type 2 message in response. But how do I construct Type 3 message to complete the authorization process?

**Comment by larryboymi** [comment]
I'm facing the same empty object for `_native_kerberos`. My use case is that I'd like to validate an incoming token.

**Comment by GeunhoKim** [comment]
In my case, I changed the `Negotiate` string in `Ssip.SecurityCredentials.acquire("Negotiate", ~)`  to `Kerberos`, `Ssip.SecurityCredentials.acquire("Kerberos", ~)`, then it worked like a charm.

It might depend on the KDC.

**Comment by ineffablep** [comment]
How can we set KeyTab Files inNode Js   instead of password after  var kerberos = new Kerberos();

**Comment by corsen2000** [comment]
Same issue here `this._native_kerberos = new KerberosNative(); ` returns an empty object with no functions.

Any suggestions would be appreciated.

**Comment by gabrielmig** [comment]
I am facing the same issue with the this._native.kerberos object empty inside the librerie js
I develop my app on VS2017 ( i have the building tools v120 installed too) and i execute it with chrome but i keep getting the same error  this._native_kerberos.authUserKrb5Password is not a function

**Comment by BorntraegerMarc** [comment]
Is there an fix for this issue?

**Comment by sandorfal** [comment]
I try to use on windows 10 the kerberos module alone and have also the problem of empty object :
---- code :
var Kerberos = require('kerberos').Kerberos;
var kerberos = new Kerberos();
console.log( 'kerberos instance : ' + JSON.stringify(kerberos) );
...
---- result :
kerberos instance : {"_native_kerberos":{}}
httpget - submitting to dtslapps.everteam.com with authorization header: undefined
httpget - 401 received
D:\test\krb\node_modules\kerberos\lib\kerberos.js:26
  return this._native_kerberos.authGSSClientInit(uri, flags, credentialsCache, callback);
                               ^
TypeError: this._native_kerberos.authGSSClientInit is not a function
    at Kerberos.authGSSClientInit (D:\test\krb\node_modules\kerberos\lib\kerberos.js:26:32)
----

I compiled it OK like said with the npm kerberos page, I also compiled it with visusalstudio with same build tools that the one installed with npm.

Please did somebody found a solution ?
It is impossible to use it because of this empty object...
Thanks

**Comment by sandorfal** [comment]
Hello please could you help because I cannot see what is wrong...
I have the same error than above. I'm on window 10.
I installed the module exactly like described on the page https://www.npmjs.com/package/kerberos, and it compiles ok and produces kerberos\build\Release\kerberos.node (174 592 bytes).

Then I try this code :
var Kerberos = require('kerberos').Kerberos;
var kerberos = new Kerberos();
kerberos.authGSSClientInit( ... );
Tracing into it with Chrome or VS Code I see that the je object contains the authGSSXxxx functions, but the _native_kerberos object does not contain what it should :
![image](https://user-images.githubusercontent.com/17699532/36344390-efe05fc2-1419-11e8-94e7-4c0591211d4a.png)
So when I execute the kerberos.authGSSClientInit like here :
![image](https://user-images.githubusercontent.com/17699532/36344421-492088aa-141a-11e8-88b3-71585e82cafc.png)
the yellow line throws : 
TypeError: this._native_kerberos.authGSSClientInit is not a function
    at Kerberos.authGSSClientInit (d:\test\krb\node_modules\kerberos\lib\kerberos.js:26:32)

So I think that this line in kerberos.js does not do its work :
![image](https://user-images.githubusercontent.com/17699532/36344468-f94e03c4-141a-11e8-9f19-d6312d04bc5f.png)

I'd like to debug further, please give me hints...
Thanks

**Comment by jmrog** [comment]
I am also struggling to get this working on Windows. I initially had the same issue as @sandorfal and the OP (@pendo324). Using @tlbdk's suggested changes, plus the correction by @GeunhoKim, I was able to get around these errors. However, after I call `SSIP.SecurityCredentials.acquire`, I now receive the error: `SEC_E_NO_CREDENTIALS: No credentials are available in the security package." (Before I switched from 'Negotiate' to 'Kerberos', as @GeunhoKim suggested, the browser would simply crash.) This is happening after I have successfully obtained a ticket using MIT Kerberos on my Windows machine. Does anyone have any suggestions regarding this error? I must be doing something wrong, but I can't figure out what. :-/

**Comment by sandorfal** [comment]
@jmrog : Is your account authenticated with a kerberos domain ? My understanding of this kerberos module is that it uses the windows API which get the ticket (credentials) from the domain at sign on and stores it on the machine. So perhaps that yourMIT kerberos does not stores the ticket at a place usable by the windows API... Then the windows API would tell that there is no credentials available.

**Comment by jmrog** [comment]
@sandorfal Thanks for responding. I have a suspicion that what you mentioned is indeed what is happening. Specifically, this...

> So perhaps that yourMIT kerberos does not stores the ticket at a place usable by the windows API

...is what I think is happening. So perhaps my remaining issue isn't an issue with this library, but rather with my particular setup right now. I'll continue investigating.

**Comment by sandorfal** [comment]
I confirm that the example of @tlbdk works for me (thank you very much @tlbdk !) with the "acquire("**Negotiate**", ...)". My machine is part of a kerberos domain.
