### ISSUE TITLE
Getting a ticket granting ticket

### ISSUE THREAD

**Issue by willm** [mongodb-js/kerberos#52]
Hi,

I'm quite new to kerberos so sorry if I've misunderstood something. I've managed to use this package to access a protected resource, however, I need to run `kinit` as each user before in order to have a ticket granting ticket to provide. Is there a way I can use this module to do the job `kinit` does? Ideally, I'd like something like this.

``` javascript
kerberos.getTicketGrantingTicket(user, password, () => {
    //ticket granting ticket is saved to my local store and available from `klist -a`
    kerberos.authGSSClientInit(`HTTP@${host}`, flag, (err, context) => {
        kerberos.authGSSClientStep(context, err => {
            //make request with `context.response` in authorisation header
        });
    });
});

```

**Comment by willm** [comment]
I have managed to do this with the [krb5](https://github.com/adaltas/node-krb5) package but I don't think I can aquire a service ticket from it. DO the kerberos and krb5 packages fulfil a different purposes? Here's how I achieved what I mention with krb5.

```javascript
const krb5 = require('krb5');

krb5({
    service_fq: 'HTTP@REALM',
    principal: 'user@REALM',
    password: 'password'
}).kinit(err => {
    if(err) { throw err; }
});
```

after this, I can see the ticket granting ticket in my local cache by running `klist -A`

**Comment by GeunhoKim** [comment]
+1
before using `kerberos.authGSSClientStep(context, err)`, it needs to execute the command `kinit $username`.

**Comment by basraven** [comment]
+1
And please provide some documentation on this

**Comment by mbroadst** [comment]
@willm the kerberos package is for authentication using kerberos not for configuring kerberos/kdcs on a local system.
