### ISSUE TITLE
Allow for linking to a prebuild modules

### ISSUE THREAD

**Issue by mlucool** [mongodb-js/kerberos#56]
Is it possible to allow for a prebuilt version of the kerberos package? Building/installing over and over again is the slowest part of our builds. Phantomjs solved this by allowing for it to be [found in the path](https://www.npmjs.com/package/phantomjs-prebuilt#using-phantomjs-from-disk). What do you think of doing something similar?

**Comment by mbroadst** [comment]
@mlucool there are prebuilt binaries for v1.0.0 for osx/linux64/win64. We will automate this more in the future, but for now this should work!
