### ISSUE TITLE
Retriving result from callback triggers core dump

### ISSUE THREAD

**Issue by Suraiya-Hameed** [mongodb-js/kerberos#61]
I'm in the process of using this package as dependency to add kerberos authentication for [tedious driver](https://github.com/tediousjs/tedious). This package rocks! reduced a lot of effort ;)

I have trouble accessing the GSS status code after initializing security context(`authGSSClientStep`). The `result` aka `info[1]` returned is `typeof symbol` in nodejs, due to `if` condition [here](https://github.com/christkv/kerberos/blob/master/lib/kerberos.cc#L958). 
If execution flows through `else` condition, there is no trouble accessing the return value. I'm wondering why this condition was introduced and how to retrieve the status code from the result? 
Any help is greatly appreciated!

**Comment by mbroadst** [comment]
Hi @Suraiya-Hameed, the API for v1.0.0 has changed, but should be far easier to use for these purposes. Please let us know if you find issues with the new API.
