### ISSUE TITLE
Implementation Details

### ISSUE THREAD

**Issue by coreylarew** [mongodb-js/kerberos#67]
Is there anything on implementation details on this? I am currently working on a Node express app that needs to use Kerberos to authorize access to the app.  Currently I am using NTLM however this will not be an option for long.

**Comment by jgupta3** [comment]
Hi, have got success to implement Kerberos ? if yes please help me i'm facing problem with kerberos implementation.

**Comment by mbroadst** [comment]
Hi, please see the documentation for the v1.0.0 release, I believe your issues should all be solved by this release.
