### ISSUE TITLE
package version to node compatible version

### ISSUE THREAD

**Issue by Kashio** [mongodb-js/kerberos#75]
Is there any documentation on what version of the package is compatible with what node version in-order to perform a successful build ?

**Comment by mbroadst** [comment]
@Kashio this module is supported with all LTS versions of node.js

**Comment by Kashio** [comment]
I use node 6.9.4 and I get alot of compilation errors regarding undefined types such as
`error: no type named 'GCEpilogueCallback' in 'v8::Isolate'`
What should I do then, since it's LTS version?

**Comment by mbroadst** [comment]
@Kashio ah! Apologies, it looks like something with the recent nan update broke support for Node 6, I've created a ticket [here](https://jira.mongodb.org/browse/NODE-1525) to track this. Please follow along there

**Comment by Kashio** [comment]
Is it specific to Node 6, can I use other version maybe? Currently I'm forced to use it in my workspace but I can try to change it if that's the case.

**Comment by mbroadst** [comment]
@Kashio the travis build indicates support for Node 8 and 10

**Comment by Kashio** [comment]
@mbroadst Awesome good to know :)
