### ISSUE TITLE
Visual Studio c++ 2010 is necessary？

### ISSUE THREAD

**Issue by penetest** [mongodb-js/kerberos#78]
Hi，I  have some questions：
    Visual Studio c++ 2010 is necessary？ I also make it Compiled successfully by Visual Studio c++ 2015， But during my use, the following some problems：
  
npm run dev（running my nodejs project）

NODE_ENV:development
 94% asset optimization

**ERROR  Failed to compile with 5 errors                                                                                                                                                                                   10:03:06

These relative modules were not found:

* ../build/Release/kerberos in ./~/kerberos/lib/kerberos.js
* ../../../build/Release/kerberos in ./~/kerberos/lib/win32/wrappers/security_credentials.js, ./~/kerberos/lib/win32/wrappers/security_context.js and 2 others**

**Comment by mbroadst** [comment]
No Visual Studio C++ 2010 is _not_ necessary
