### ISSUE TITLE
kerberos shows  errors

### ISSUE THREAD

**Issue by penetest** [mongodb-js/kerberos#83]
ERROR  Failed to compile with 1 errors                                                                                                                                                                                   17:11:54

 error  in ./~/kerberos/build/Release/kerberos.node

Module parse failed: D:\workspaces\UiJsProjects\avue\node_modules\kerberos\build\Release\kerberos.node Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

**Comment by mbroadst** [comment]
@penetest what version of kerberos are you building here? How are you using the module? Can you please tell us what operating system and compiler you are using.
