### ISSUE TITLE
Not able to upgrade to latest version 1.0.0  with node v10

### ISSUE THREAD

**Issue by yogeshbansal** [mongodb-js/kerberos#84]
I tried to upgrade Kerberos to the latest version with node v10. I am getting this error. With kerberos 0.0.24 it's working fine

> kerberos@1.0.0 install /home/ec2-user/application/apiserver-v2/node_modules/kerberos
> prebuild-install || node-gyp rebuild

prebuild-install WARN install /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/ec2-user/application/apiserver-v2/node_modules/kerberos/build/Release/kerberos.node)
make: Entering directory `/home/ec2-user/application/apiserver-v2/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
  CXX(target) Release/obj.target/kerberos/src/unix/base64.o
  CXX(target) Release/obj.target/kerberos/src/unix/kerberos_gss.o
  CXX(target) Release/obj.target/kerberos/src/unix/kerberos_unix.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lkrb5
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lgssapi_krb5
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/kerberos.node] Error 1
make: Leaving directory `/home/ec2-user/application/apiserver-v2/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.14.55-62.37.amzn1.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/application/apiserver-v2/node_modules/kerberos
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kerberos@1.0.0 install script.

**Comment by mbroadst** [comment]
@yogeshbansal please follow the install instructions and install kerberos libraries on your local system. As you can see above the relevant link errors are:
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lkrb5
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lgssapi_krb5
```
