### ISSUE TITLE
Get client username from KerberosServer.step

### ISSUE THREAD

**Issue by accerqueira** [mongodb-js/kerberos#87]
It looks like that information is placed in internal KerberosServer state, on the binary node module (https://github.com/mongodb-js/kerberos/blob/master/src/unix/kerberos_gss.cc#L590-L598), but I don't know much about how node c++ interface works, and I see no docs here about that.

Is there a way to get this information?

**Comment by accerqueira** [comment]
Nevermind.
Just found accessor for username on KerberosServer::Init and tested with console.log on initializeServer resolve value.
Thanks!

**Comment by mbroadst** [comment]
Hi @accerqueira! Thanks for pointing this out, we seem to be missing documentation for the attached properties of both `KerberosClient` and `KerberosServer`. I created this [ticket](https://jira.mongodb.org/browse/NODE-1721) to track that work.
