### ISSUE TITLE
user test is wrong in win32 code

### ISSUE THREAD

**Issue by bigianb** [mongodb-js/kerberos#88]
I've been working on a node client making a REST call to a SharePoint server via the Negotiate authentication using this library. I came across an issue which stopped it from working.

I can't easily raise a PR from work as we're heavily fire-walled in that respect, but the fix is simple enough to describe here.

In kerberos_sspi.cc you check for user to be null .... but it never is because it is the results of a std::string c_str() call. So, instead of saying:

`if (user) {`

you need to say

`if (ulen > 0){`

The following 2 lines need modifying.

https://github.com/mongodb-js/kerberos/blob/master/src/win32/kerberos_sspi.cc#L71

https://github.com/mongodb-js/kerberos/blob/master/src/win32/kerberos_sspi.cc#L95

Without this change, you get an NTLM token rather than a kerberos token ... which may work in some situations but does not in mine.

The diff is:
```
diff --git a/src/win32/kerberos_sspi.cc b/src/win32/kerberos_sspi.cc
index 84dc503..0e1f1e0 100644
--- a/src/win32/kerberos_sspi.cc
+++ b/src/win32/kerberos_sspi.cc
@@ -68,7 +68,7 @@ auth_sspi_client_init(WCHAR* service,
         return sspi_error_result_with_message("Ran out of memory assigning service");
     }
 
-    if (user) {
+    if (ulen > 0) {
         authIdentity.User = (unsigned short*)user;
         authIdentity.UserLength = ulen;
         authIdentity.Password = (unsigned short*)password;
@@ -92,7 +92,7 @@ auth_sspi_client_init(WCHAR* service,
                                        /* LogonID (We don't use this) */
                                        NULL,
                                        /* AuthData */
-                                       user ? &authIdentity : NULL,
+                                       (ulen > 0) ? &authIdentity : NULL,
                                        /* Always NULL */
                                        NULL,
                                        /* Always NULL */
```

**Comment by mbroadst** [comment]
@bigianb thanks for the report! I've created #89 to address this issue. I was trying to make the code safer by using `std::string`, but no good deed goes unpunished *shakes fist at sky*. It seems in my email you had mentioned another issue you were having, did that get lost here?

**Comment by bigianb** [comment]
Thanks Matt! The other issue was just me being stupid in the client code and calling step too many times. I edited the issue to remove that hence your confusion.
With the user fix it all works fine connecting to sharepoint within a big corporate environment.

Ian

**Comment by mbroadst** [comment]
Hi @bigianb, v1.1.1 has been released with your fix as well as a fix for authenticating without password or domain. Please let us know if you run into any other issues!
