### ISSUE TITLE
NPM Install defaults to mongodb-js/kerberos/releases

### ISSUE THREAD

**Issue by siva-srini** [mongodb-js/kerberos#90]
My organization maintains a private repository from which we install all packages.  Our local repository puts the packages that we need.  And kerberos is one of it.

So, "npm i kerberos" is accessed from local repository, but while its getting installed, within the scripts its trying to download platform based package (kerberos-v1.1.2-node-v57-linux-x64.tar.gz) from https://github.com/mongodb-js/kerberos/releases

Could you provide the environment variable that we can use in .npmrc file to point to our local repository for these files.

Or, could you add an enhancement to do the above work around or let us know how install manually without downloading from github. Our servers does not communicate to github and the install fails.

Please help..

**Comment by mbroadst** [comment]
Hi @siva-srini! We use `prebuild-install` to make it easier for end users to install without having to build the module each time. They have instructions on how to accomplish what you're asking for [here](https://github.com/prebuild/prebuild-install#custom-binaries). Please let us know if there are any issues with those instructions.

**Comment by siva-srini** [comment]
Great.  This worked!! Thanks for your help.
