### ISSUE TITLE
defaultRealm in checkPassword function is not optional

### ISSUE THREAD

**Issue by velezsarain** [mongodb-js/kerberos#91]
The documentation for checkPassword implies that the argument defaultRealm is optional (argument is inside brackets)
```
 * @kind function
 * @param {string} username The Kerberos user name. If no realm is supplied, then the `defaultRealm` will be used.
 * @param {string} password The password for the user.
 * @param {string} service The Kerberos service to check access for.
 * @param {string} [defaultRealm] The default realm to use if one is not supplied in the user argument.
 * @param {function} [callback]
 * @return {Promise} returns Promise if no callback passed
```
Yet the implementation says otherwise, as defaultRealm is not assigned a default value and the validateParameter function will fail as the defineOperation monkey patcher does not have a special case for the defaultRealm argument (similar to the "options" special case)
```
const checkPassword = defineOperation(kerberos.checkPassword, [
  { name: 'username', type: 'string' },
  { name: 'password', type: 'string' },
  { name: 'service', type: 'string' },
  { name: 'defaultRealm', type: 'string' }
]);
```
Either the documentation is wrong, and defaultRealm should be marked as a required argument, or the implementation is wrong, and defaultRealm should be assigned a default value or have a special case in the defineOperation function.

**Comment by mbroadst** [comment]
Addressed in #93
