### ISSUE TITLE
GSS and OID flags should not be exported at root level namespace

### ISSUE THREAD

**Issue by velezsarain** [mongodb-js/kerberos#92]
All flags in the kerberos package are exported at the root level namespace
```
// GSS Flags
const GSS_C_DELEG_FLAG = 1;
const GSS_C_MUTUAL_FLAG = 2;
const GSS_C_REPLAY_FLAG = 4;
const GSS_C_SEQUENCE_FLAG = 8;
const GSS_C_CONF_FLAG = 16;
const GSS_C_INTEG_FLAG = 32;
const GSS_C_ANON_FLAG = 64;
const GSS_C_PROT_READY_FLAG = 128;
const GSS_C_TRANS_FLAG = 256;

// GSS_OID
const GSS_C_NO_OID = 0;
const GSS_MECH_OID_KRB5 = 9;
const GSS_MECH_OID_SPNEGO = 6;
```
This pollutes the root level namespace with a lot of values that are not relevant to the user unless they are using the functions that require these flags.

I would suggest exporting these values as two additional namespaces

```
export const GssFlags = {
  GSS_C_DELEG_FLAG: 1,
  GSS_C_MUTUAL_FLAG: 2,
  GSS_C_REPLAY_FLAG: 4,
  GSS_C_SEQUENCE_FLAG: 8,
  GSS_C_CONF_FLAG: 16,
  GSS_C_INTEG_FLAG: 32,
  GSS_C_ANON_FLAG: 64,
  GSS_C_PROT_READY_FLAG: 128,
  GSS_C_TRANS_FLAG: 256
};

export const GssOidFlags = {
  GSS_C_NO_OID: 0,
  GSS_MECH_OID_KRB5: 9,
  GSS_MECH_OID_SPNEGO: 6
};
```
This will not only free up the kerberos namespace of a lot of values, but will allow for clearer documentation and for checking that the functions are not used with the wrong arguments. I am currently writing the TypeScript type definition file for this package, and the current implementation unfortunately doesn't allow me to type check these flags.

I understand this is a breaking change, but these values could be added alongside the current declared ones instead as a compromise.

**Comment by mbroadst** [comment]
@velezsarain is this an actual problem, or just something you feel cool be cleaner?

**Comment by velezsarain** [comment]
No, this is not an actual problem, only a suggestion. The current implementation works just fine.

**Comment by mbroadst** [comment]
@velezsarain ah okay! I've created [NODE-1758](https://jira.mongodb.org/browse/NODE-1758) to track this. Thanks for your report.
