### ISSUE TITLE
start of base64 encoded token occasionally corrupted from client.step('',function(err,token)

### ISSUE THREAD

**Issue by contentengineer** [mongodb-js/kerberos#94]
Using kerberos library on **node.js** v8 (Win2012 and Win7) to undertake HTTP Negotiate calls to an HTTP SOAP(XML) web service, using three step process based on examples:

1. kerberos.initializeClient('HTTP/host.realm@REALM',{ user: 'user@domain.tld',password: '...'},function(err,client){ ...
2. client.step('',function(err,kerberosToken){ ..
3. adding header 'Authorization':'Negotiate ' + kerberosToken 
4. making httpreq[method](url,kerberosOptions,function(err,result){ ...

Occasionally we are seeing a token being returned from the second step `client.step('',function(err,token){ })` that is not base64 encoded. The first 12-15 characters are not base64 characters and include the following ASCII hex values: 70 C2 83 13 C2 BB C2 B9 01 20 16 10 C2 BB C2 B9 01

Any thoughts on what could be causing this corruption?

Looked at `kerberos_sspi.cc`  which uses Crypt32.dll  `CryptBinaryToStringA()` for base64 conversion of the outBufs in auth_sspi_client_step() but nothing standsout as a problem so far.

**Comment by mbroadst** [comment]
Hi @contentengineer, do you have bandwidth to test solutions on your end? Could you try modifying the build to include the base64 implementation in the `unix` directory, and using that function instead of the one based on `CryptBinaryToStringA`?
