### ISSUE TITLE
Kerberos module segmentation fault after upgrading CentOS Linux 7.5.1804 to CentOS Linux 7.6.1810

### ISSUE THREAD

**Issue by Casm82** [mongodb-js/kerberos#96]
Hello.
After upgrading CentOS Linux 7.5.1804 to CentOS Linux 7.6.1810 node.js kerberos module crash.

I checked on Node.js 8.14.0 and 10.14.1.
On CentOS Linux 7.5.1804 everything works without error, on CentOS Linux 7.6.1810 the module causes a crash.

I use this example.
https://gist.github.com/Casm82/6dcbade764faf36a0ca87225b61db857

I created keytab on Windows domain member server
>> ktpass -princ HTTP/centos.domain.org@DOMAIN.ORG -mapuser user_krb@domain.org -crypto ALL -ptype KRB5_NT_PRINCIPAL -pass ****** -out %tmp%\krbAuth.keytab

On Node.js server (Centos Linux) I copied keytab file and set environment variable: export KRB5_KTNAME=/path/krbAuth.keytab

On the client (Windows 10, domain member) I added the site http://centos.domain.org to the Local Intranet Zone.

The example startup log is the following:
Centos 7.5
https://gist.github.com/Casm82/a25242d07ca41b1364f49b13b769482c

Centos 7.6
https://gist.github.com/Casm82/4691d18366d768125975656b1fb7f78f

Command ldd output:
Centos 7.5
https://gist.github.com/Casm82/7045b294bfec6bbaae6f343ef6451cf3

Centos 7.6
https://gist.github.com/Casm82/a1c0bc31c7b3f79592609454bc15fd9b

**Comment by mbroadst** [comment]
Hi @casm82, is it possible to run your example with the [segfault-handler](https://github.com/ddopson/node-segfault-handler) module enabled? A backtrace would be most helpful for this segfault.

**Comment by Casm82** [comment]
@mbroadst
Yes, I will try to run the example with the module segfault-handler . I need 2-3 days to create a test servers.

**Comment by Casm82** [comment]
@mbroadst
I added a module segfault-handler to the example 
https://gist.github.com/Casm82/ffed0a7b365ad5b988dcfdfdbdf0eef2
the module showed very little information (crash.log): 
```
PID 20345 received SIGSEGV for address: 0x75
```
After I launched the example as follows: node inspect krb_test.js
Output was:
```
break in file:///home/node/krbAuth/krb_test.js:14
 12     if (err) console.error(err);
 13     //check ticket
>14     krbServer.step(ticket, function(err) {
 15       if (err) console.error(err);
 16       console.log(krbServer);
debug> n
< PID 20487 received SIGSEGV for address: 0x75

```

**Comment by Casm82** [comment]
I compiled the Node.js 10.14.2 from the source with options
`./configure --debug --gdb --prefix=/opt/node-debug`
Simplified example https://gist.github.com/Casm82/71ca16932e03df1a6afd3974c9204633
And launched the example through the debugger
`gdb --args /opt/node-debug/bin/node krb_test.js`
Full log: https://gist.github.com/Casm82/9b49ca64f0c92bfed96fa922b968ef02
Maybe it can help.

**Comment by Casm82** [comment]
After update to krb5-libs-1.15.1-37, krb5-workstation-1.15.1-37 error disappeared.
Problem solved.
